### ISSUE TITLE
CleanBC: Change streaks to dots in legend

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk-clean-bc#49] opened 2023-01-19 00:11 UTC
> [Open in MURAL](https://app.mural.co/t/datasystemsandservices8142/m/datasystemsandservices8142/1674081183025?wid=0-1674081665400) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CleanBC JIRA to GH Integration - CITZ – BCDS – Data Systems and Services

**Comment by NicoledeGreef** [comment] 2023-01-19 00:45
this may be a duplicate of #37 ?

**Comment by michaelpnelson** [comment] 2023-01-19 18:24
Yes, this is a duplicate of #37. I've added the "duplicate" label and will close this.

**Closed by michaelpnelson** 2023-01-19 18:24 UTC
Labels: duplicate
